### PR TITLE
Add --owner to project creation

### LINKED ISSUE #107: Allow defining ownership on all project creation situations
User should be able to select project ownership whenever he creates a new project through `vh`.

The most obvious situation with enterprise accounts where most, if not all, projects should be under the organization or a team.

### PR DESCRIPTION
**Pull request by akx**
Fixes #107

### CODE REVIEW

**Comment by ruksi** [comment]
I think all of the mid-process project generations should also ask for ownership as part of this PR (e.g. `vh init` [C])

**Comment by ruksi** [comment]
ping

**Comment by akx** [comment]
> I think all of the mid-process project generations should also ask for ownership as part of this PR (e.g. `vh init` [C])

Mmm, we'd need an API for retrieving possible ownerships.

**Comment by akx** [comment]
@ruksi Ready for re-review

**Comment by ruksi** [comment]
still doesn't prompt owner in `vh init` project create? will that be in a separate PR?

**Comment by ruksi** [comment]
at least the vh init test doesn't test that even that it does the `[C]` route

**Comment by akx** [comment]
> still doesn't prompt owner in `vh init` project create? will that be in a separate PR?

I'm pretty sure I tried it out myself... It'll only prompt when there is more than one ownership option, anyway.

**Comment by ruksi** [comment]
I'll take your word for it :ok_hand:

**Pull request merged**
