### PR TITLE
Create dependabot.yml for version bumps

### PR DESCRIPTION
**Pull request by akx**
Refs #216, #217 – let's see if Dependabot can keep us up to date.

See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

### CODE REVIEW

**Review by ruksi — APPROVED** [review]
could also just check for upgrade on the packages mentioned in the issue, but I see no harm in checking all dependencies 

ref https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow

**Comment by akx** [comment]
@ruksi Yeah, I figured we can fine-tune the configuration later :)

**Comment by ruksi** [comment]
haven't tried the Dependabot `pip` that sources from `setup.cfg` and without a lock file but let's see if it works :wink:

**Comment by akx** [comment]
@ruksi Judging by the 5 new PRs that just appeared, it doth work...

**Comment by akx** [comment]
Oh, right. 😅

**Pull request merged**
